const data = {
    products: [
      {
        name: 'productAName',
        description: '',
        category: 'Pharma',
        price: 100,
        token: 'productA-Token',
        brand: 'Teva',
        countinstock: 6,
        rating: 2.5,
        numReviews: 100,
        image: '/images/beautycare.jpeg',
      },
      {
        name: 'productBName',
        description: '',
        category: 'Pharma',
        price: 150,
        token: 'productB-Token',
        brand: 'Teva',
        countinstock: 3,
        rating: 3,
        numReviews: 10,
        image: '/images/bosil.jpeg',
      },
      {
        name: 'productCName',
        description: '',
        category: 'Pharma',
        price: 800,
        token: 'productC-Token',
        brand: 'Teva',
        countinstock: 9,
        rating: 1,
        numReviews: 65,
        image: '/images/megaglu.jpeg',
      },
      {
        name: 'productDName',
        description: '',
        category: 'Pharma',
        price: 120,
        token: 'productD-Token',
        brand: 'Teva',
        countinstock: 15,
        rating: 5,
        numReviews: 130,
        image: '/images/omega3.jpeg',
      },
  
  
      {
          name: 'productEName',
          description: '',
          category: 'Pharma',
          price: 100,
          token: 'productE-Token',
          brand: 'Teva',
          countinstock: 6,
          rating: 2.5,
          numReviews: 100,
          image: '/images/beautycare.jpeg',
        },
        {
          name: 'productFName',
          description: '',
          category: 'Pharma',
          price: 150,
          token: 'productF-Token',
          brand: 'Teva',
          countinstock: 3,
          rating: 3,
          numReviews: 10,
          image: '/images/bosil.jpeg',
        },
        {
          name: 'productGName',
          description: '',
          category: 'Pharma',
          price: 80,
          token: 'productG-Token',
          brand: 'Teva',
          countinstock: 9,
          rating: 1,
          numReviews: 65,
          image: '/images/megaglu.jpeg',
        },
        {
          name: 'productHName',
          description: '',
          category: 'Pharma',
          price: 120,
          token: 'productH-Token',
          brand: 'Teva',
          countinstock: 15,
          rating: 5,
          numReviews: 130,
          image: '/images/omega3.jpeg',
        },
    ],
  };
  
  export default data;