import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: bcrypt.hashSync('12345')
    }
  ],
  products: [
    {
      // _id: 1,
      name: "productAName",
      description: "",
      category: "Pharma",
      price: 100,
      token: "productA-Token",
      brand: "Teva",
      countinstock: 0,
      rating: 2.5,
      numReviews: 100,
      image: "/images/beautycare.jpeg",
    },
    {
      //_id: 2,
      name: "productBName",
      description: "",
      category: "Pharma",
      price: 150,
      token: "productB-Token",
      brand: "Teva",
      countinstock: 3,
      rating: 3,
      numReviews: 10,
      image: "/images/bosil.jpeg",
    },
    {
      //_id: 3,
      name: "productCName",
      description: "",
      category: "Pharma",
      price: 800,
      token: "productC-Token",
      brand: "Teva",
      countinstock: 9,
      rating: 1,
      numReviews: 65,
      image: "/images/megaglu.jpeg",
    },
    {
      //_id: 4,
      name: "productDName",
      description: "",
      category: "Pharma",
      price: 120,
      token: "productD-Token",
      brand: "Teva",
      countinstock: 15,
      rating: 5,
      numReviews: 130,
      image: "/images/omega3.jpeg",
    },

    {
      //_id: 5,
      name: "productEName",
      description: "",
      category: "Pharma",
      price: 100,
      token: "productE-Token",
      brand: "Teva",
      countinstock: 6,
      rating: 2.5,
      numReviews: 100,
      image: "/images/beautycare.jpeg",
    },
    {
      //_id: 6,
      name: "productFName",
      description: "",
      category: "Pharma",
      price: 150,
      token: "productF-Token",
      brand: "Teva",
      countinstock: 3,
      rating: 3,
      numReviews: 10,
      image: "/images/bosil.jpeg",
    },
    {
      //_id: 7,
      name: "productGName",
      description: "",
      category: "Pharma",
      price: 80,
      token: "productG-Token",
      brand: "Teva",
      countinstock: 9,
      rating: 1,
      numReviews: 65,
      image: "/images/megaglu.jpeg",
    },
    {
      //_id: 8,
      name: "productHName",
      description: "",
      category: "Pharma",
      price: 120,
      token: "productH-Token",
      brand: "Teva",
      countinstock: 15,
      rating: 5,
      numReviews: 130,
      image: "/images/omega3.jpeg",
    },
  ],
};

export default data;
